### ISSUE TITLE
Lookahead Bug in Current Price Method 

### ISSUE THREAD

**Issue by RaedShabbir** [notadamking/tensortrade#106]
In the current price method for simulated exchange, the step at which the price is accessed is one step ahead. This is because at the end of the next_observation method we call self._current_step += 1. Then the step method is called following this. 

The below has worked for me to fix this. 
Proposed Solution:
Add a step attribute to trade objects, then all methods for current price and what not can refer to "trade.step".  When creating the trade object init this parameter with self._current_step - 1.
I believe the ability to access the step at which a trade was made through its trade object is generally useful feature.

**Comment by notadamking** [comment]
If you take a look at the order of execution within the environments step function, you can see that _take_action is called before_next_observation.
I.e. any trades made using current_price are made using the correct price, since current_step has not been updated yet.
There is a possibility of a problem with _get_reward being called after _next_observation, as the reward would be based on the current_step of the next time step.
Though, this could also be desired behavior.
And with that kept in mind, any RewardScheme can then use current_step - 1 wherever necessary. So again, I believe all of this is desired behavior and execution, though please correct me if I am wrong.

**Comment by RaedShabbir** [comment]
I still think this may be an issue because during reset next_observation is called prior to _take_action is called. Let me know what you think, I added more details and code in #development on disc. If I'm not mistaken I'll share the proposed solution, an easy fix.
