### ISSUE TITLE
why net_worth charts are different between posted article and github notebook file?

### ISSUE THREAD

**Issue by maochaokuo** [notadamking/tensortrade#86]
hi,

I appreciate the TensorTrade_Tutorial.ipynb file got fixed, and I may run it myself. However, I have a question about the content. The networth chart, what we really care about as the final result, is different between the one in the Medium article (title: "Trade and Invest Smarter -- The Reinforcement Learning Way) and the one (actually two) in TensorTrade_Tutorial.ipynb file.

The networth chart in Medium article, rise slowly and smoothly. Refer to MediumArticle.png
And the two networth charts in TensorTrade_Tutorial.ipynb, just fall all the way (1st one) or rise shortly then fall. Refer to github-chart1.png and github-chart2

So what went wrong? What is different? It is not easy for us to choose a trading strategy to all the way lose, unless the tradebot completely trade OPPOSITE TO THE OPTIMIZED STRATEGY. Do you mind to take a look?

![github-chart2](https://user-images.githubusercontent.com/6857537/68065653-51f54c80-fd67-11e9-855a-132b96aa1ad8.png)
![github-chart1](https://user-images.githubusercontent.com/6857537/68065654-51f54c80-fd67-11e9-8811-95bef77d3840.png)
![MediumArticle](https://user-images.githubusercontent.com/6857537/68065655-51f54c80-fd67-11e9-8af6-a7139684c03d.png)

.png

**Comment by codeninja** [comment]
One of the primary differences is in the episodes that the neural network
agent was able to train on. The example in the source is set to train for
10 episodes so that it can finish within a demo period. The agent you see
represented in the final image was tuned over many thousand episodes. This
of course takes time that a demo would not have (weeks or more depending on
how you train it).

The framework has also undergone somewhat of a surge of development
recently as people have joined the platform. We are still working out the
kinks as we race towards Alpha. The 2.0rc1 that is on the master branch now
is substantially different than the 0.16 version that existed 2 weeks ago.

Thanks,
Dallas
---------------------------------------
*Professional leader of highly performant engineering teams since 1997*
*512.923.4426 | Github  <https://github.com/codeninja>| Twitter
<https://twitter.com/dallaspool>| Linkedin
<https://linkedin.com/in/dallaspool>*

**Comment by maochaokuo** [comment]
Hi Dallas:

I just updated everything, from github tensortrade, including the TensorTrade_Tutorial.ipynb file. I changed steps to episodes(=50), but still get similar result, as attached.
![github-chart1episodes50](https://user-images.githubusercontent.com/6857537/68073151-f909d080-fdc7-11e9-9768-1a0b4a112d8f.png)

**Comment by maochaokuo** [comment]
Daily result just come out. It is a bit better, but eventually still
.....
![github-chart2episodes50](https://user-images.githubusercontent.com/6857537/68073213-79c8cc80-fdc8-11e9-909d-c6d49f9a73db.png)

**Comment by codeninja** [comment]
50 episodes is not nearly enough training for a production system. Train
for 1000 episodes and your results should improve to production performance
levels.

As with any framework, the outcome will be dependent on how you implement
your network, your rewards, and your strategy. Also, you must test your
network on data which it has never seen before to ensure it's performance
is not overfit to the training environment. (FBMExchange will do this
automatically every iteration.)

Thanks,
Dallas
---------------------------------------
*Professional leader of highly performant engineering teams since 1997*
*512.923.4426 | Github  <https://github.com/codeninja>| Twitter
<https://twitter.com/dallaspool>| Linkedin
<https://linkedin.com/in/dallaspool>*

**Comment by maochaokuo** [comment]
I get it. However, the difference between the article and Jupiter notebook file is misleading and confusing. Anyway, I look forward to the framework to become available in the near future. Thank you for your hard work and contribution.
